# Generated by Django 3.2 on 2021-04-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('aboutMe', models.TextField(max_length=2000)),
                ('address', models.TextField(max_length=200)),
                ('github_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
                ('linkedIn_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
                ('college', models.CharField(max_length=200)),
                ('degree_college', models.CharField(max_length=200)),
                ('cgpa_college', models.CharField(max_length=200)),
                ('_12th', models.CharField(max_length=200)),
                ('score_12th', models.CharField(max_length=200)),
                ('stream_12th', models.CharField(max_length=200)),
                ('time_college', models.CharField(max_length=200)),
                ('prev_work_company', models.CharField(max_length=200)),
                ('prev_work_role', models.CharField(max_length=200)),
                ('prev_work_location', models.CharField(max_length=200)),
                ('prev_work_description', models.TextField(max_length=2000)),
                ('proj_title', models.CharField(max_length=200)),
                ('proj_description', models.TextField(max_length=2000)),
                ('languages', models.TextField(max_length=200)),
                ('tools_and_framework', models.TextField(max_length=200)),
            ],
        ),
    ]
