# Generated by Django 3.2 on 2021-05-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210430_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_link',
            field=models.URLField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedIn_link',
            field=models.URLField(blank=True, db_index=True, max_length=128),
        ),
    ]
